// ---------- I18N (FR/EN toggle) ----------
(function () {
  var EN = {
    'nav.brandAria': 'Dar Aïcha — Home',
    'nav.mainAria': 'Main navigation',
    'nav.villa': 'The Villa',
    'nav.espaces': 'Our Spaces',
    'nav.sejourner': 'Stay',
    'nav.evenements': 'Weddings & Events',
    'nav.privatisation': 'Private Stays',
    'nav.huile': 'Estate & Olive Grove',
    'nav.region': 'Tazarka & Access',
    'nav.avis': 'Reviews',
    'nav.contact': 'Contact',
    'nav.reserver': 'Book Now',
    'nav.themeAria': 'Switch theme',
    'nav.menuAria': 'Open menu',
    'hero.scrollAria': 'Scroll down',
    'stats.suites': 'Suites',
    'stats.people': 'Guests hosted',
    'stats.guests': 'Event guests',
    'stats.olive': 'Olive grove',
    'pillars.kicker': 'Three Ways to Experience Dar Aïcha',
    'pillars.h2': 'Stay, celebrate or discover our terroir',
    'pillars.lede': 'A unique property to explore at your own pace: exclusive seasonal rental, welcoming guesthouse or immersion in our olive oil production.',
    'pillars.img1': 'Infinity pool at Villa Dar Aïcha with sun loungers and open views',
    'pillars.img2': 'Wedding reception held by the pool at Dar Aïcha, bright white décor at dusk',
    'pillars.tag1': 'Stay & Rental',
    'pillars.tag2': 'Events',
    'pillars.tag3': 'Our Brand',
    'pillars.h3-1': 'Staying at the villa',
    'pillars.h3-2': 'Events & weddings',
    'pillars.h3-3': 'Domaine Dar Aïcha',
    'pillars.p1': 'Seasonal rental or guesthouse depending on the season, for up to 25 guests.',
    'pillars.p2': 'Up to 250 guests for your weddings, engagements and private parties.',
    'pillars.p3': 'Extra virgin Koroneiki olive oil, harvested and pressed on our estate in Tazarka.',
    'villa.kicker': 'The Villa',
    'villa.h2': 'White architecture blending Tunis tradition with contemporary lines',
    'villa.lede': 'Built on a 4-hectare agricultural estate, Dar Aïcha combines the Tunis arch, local stone and modern comfort. Nine suites, generous living spaces and an infinity pool facing the horizon.',
    'villa.img1': 'Front view of Villa Dar Aïcha, white façade with golden stone and paved driveway',
    'villa.img2': 'Infinity pool with parasols overlooking the Tazarka countryside',
    'villa.img3': 'Spacious lounge with colorful Berber rugs and cushions, large glass windows',
    'villa.img4': 'Interior patio with Tunis-style arch and zellige fountain',
    'villa.img5': 'Aerial view of the Dar Aïcha property, villa surrounded by gardens and olive trees',
    'villa.img6': 'Hssin suite with double bed and traditional Tunisian craftsmanship',
    'villa.img7': 'Bathroom in traditional blue Tunisian zellige tile',
    'villa.img8': 'Dining room able to seat a large number of guests',
    'suites.kicker': 'Accommodation',
    'suites.h2': '9 suites, a unique offering',
    'suites.lede': 'Five ground-floor suites and four upstairs suites, all air-conditioned, with private bathroom and Tunisian craft décor — kilims, zellige, turned wood. Same rate regardless of suite location.',
    'suites.img1': 'Suite at Villa Dar Aïcha, double bed and white linens',
    'suites.img2': 'Hssin Suite at Villa Dar Aïcha, warm ambiance and local craftsmanship',
    'suites.h3-1': 'One Suite',
    'suites.h3-2': 'Renting the Entire Villa',
    'suites.p1': '9 air-conditioned suites with private bathroom, on the garden level or upstairs with access to the panoramic terrace.',
    'suites.p2': 'Privatize all 9 suites for a family or friends getaway, for up to 25 guests.',
    'suites.price1b': 'From 255 TND',
    'suites.price1s': '/ night, per suite (≈ €75)',
    'suites.price2b': 'On request',
    'suites.price2s': 'direct rate, no platform commission',
    'amenities.kicker': 'Amenities',
    'amenities.h2': 'All the comfort of a large Mediterranean home',
    'amenities.a1': 'Infinity pool',
    'amenities.a2': '11 bathrooms',
    'amenities.a3': 'Equipped kitchen',
    'amenities.a4': 'High-speed Wi-Fi',
    'amenities.a5': 'Air conditioning',
    'amenities.a6': 'Private parking',
    'amenities.a7': 'Garden & olive grove',
    'amenities.a8': 'Ponies, poultry & sheep',
    'amenities.a9': 'Outdoor kitchen & BBQ bar',
    'amenities.a11': 'Mini-bar & TV in every suite',
    'espaces.kicker': 'Our Spaces',
    'espaces.h2': 'An outdoor kitchen with BBQ bar, lounges opening onto the patio',
    'espaces.lede': 'Beyond the suites, Dar Aïcha comes alive in its shared spaces: the outdoor kitchen with its bar counter and BBQ corner, the indoor kitchen opening fully onto the pool, majlis-style Tunis lounges, the central patio with its zellige fountain, and a swing corner for children by the pool.',
    'espaces.kicker2': 'Outdoor Kitchen & BBQ Bar',
    'espaces.h2b': 'The perfect spot for outdoor dining',
    'espaces.p1': 'Marble bar counter, matching table and a barbecue corner sheltered behind a wrought-iron screen: the outdoor kitchen extends the patio for grilling, aperitifs and family meals facing the olive grove.',
    'espaces.li1': 'Marble bar and matching outdoor table',
    'espaces.li2': 'Equipped barbecue corner, sink and storage',
    'espaces.li3': 'Open views over the countryside and olive grove',
    'espaces.imgFeature': 'Outdoor kitchen with marble bar and BBQ corner, overlooking the Tazarka countryside',
    'espaces.img1': 'Barbecue corner of the outdoor kitchen with grill, sink and wooden storage',
    'espaces.img2': 'Outdoor kitchen viewed from the bar, wrought-iron screen',
    'espaces.img3': 'Indoor kitchen fully open to the pool and terrace',
    'espaces.img4': 'Central granite kitchen island with 5-burner cooktop',
    'espaces.img5': 'Table set with traditional Tunisian ceramic tableware',
    'espaces.img6': 'Tunis-style majlis lounge with low benches, Berber cushions and large bay windows',
    'espaces.img7': 'Lounge opening onto the kitchen through a large bay window',
    'espaces.img8': 'Large lounge with colorful Berber rugs and armchairs, marble floor',
    'espaces.img9': 'Lounge with beige benches, embroidered cushions and sheer curtains',
    'espaces.img10': 'Central vaulted patio with marble fountain and artisanal chandelier',
    'espaces.img11': 'Tiered patio fountain, view through the arches down to the sea',
    'espaces.img12': 'Patio and shaded outdoor dining area, stone colonnades',
    'espaces.img13': 'Swing corner for children by the pool, surrounded by palm trees and gardens',
    'espaces.img14': 'Swing set and play structure for children near the infinity pool',
    'sejourner.kicker': 'Stay',
    'sejourner.h2': 'Seasonal rental in high season, guesthouse the rest of the year',
    'sejourner.img': 'Terrace and pool at Dar Aïcha, calm low-season atmosphere, loungers by the water',
    'sejourner.li1': 'Full seasonal rental in high season (June–September)',
    'sejourner.li2': 'Booking by suite as a guesthouse the rest of the year',
    'sejourner.li3': 'Check-in from 3pm, check-out at 11am',
    'sejourner.li4': 'On-site contact: Fatma, the house host',
    'sejourner.cta': 'Check Availability',
    'evenements.kicker': 'Events & Receptions',
    'evenements.h2': 'Weddings, engagements and private parties for up to 250 guests',
    'evenements.lede': 'The Dar Aïcha estate transforms for your special occasions: ceremonies by the infinity pool, garden receptions, evenings under the olive trees. Large private parking and a dedicated security team throughout the event.',
    'evenements.img1': 'Wedding reception by the Dar Aïcha pool with a lit heart-shaped display',
    'evenements.img2': 'Pool area set up for an event, beige loungers and parasols',
    'evenements.img3': 'Villa Dar Aïcha lit up in the evening for an event',
    'evenements.img4': 'Aerial view of the pool terrace arranged as a white lounge for a reception',
    'evenements.card1h': 'Up to 250 guests',
    'evenements.card1p': 'Capacity for a seated dinner reception. Large private parking and security team included.',
    'evenements.card2h': 'From 3,500 to 5,500 TND',
    'evenements.card2p': 'Full estate privatization: from 3,500 TND in low season, up to 5,500 TND in high season — custom quote based on your needs.',
    'evenements.card3h': 'Tailor-made organization',
    'evenements.cta': 'Request an Event Quote',
    'priv.kicker': 'Group Stays',
    'priv.h2': 'Privatize Dar Aïcha for your retreat, workshop or seminar',
    'priv.lede': 'Dar Aïcha can be privatized entirely for your group for the duration of your stay: no other guests, no shared spaces. Nine suites, a large lounge, an equipped kitchen, a patio, an infinity pool and a 4-hectare olive grove are yours alone — the ideal setting for a wellness retreat, an olive-oil themed stay, a creative workshop or a corporate seminar.',
    'priv.imgAlt': 'Aerial view of the Dar Aïcha property, ideal for a privatized group stay',
    'priv.theme1h': 'Wellness & Yoga Retreats',
    'priv.theme1p': 'The patio, garden and olive grove offer several natural settings for your yoga, meditation or breathing sessions. Our team adapts to your schedule: meal times, special diets, quiet hours.',
    'priv.theme2h': 'Olive-Oil Themed Stay',
    'priv.theme3h': 'Creative Workshops',
    'priv.theme3p': 'Cap Bon light, olive grove lines, infinity pool blue: an inspiring setting for a painting, photography or writing residency workshop.',
    'priv.theme4h': 'Corporate Seminars',
    'priv.theme4p': 'A setting conducive to strategic thinking and team building, away from urban bustle — workshops, group activities and dinner prepared by an on-site chef.',
    'priv.inclusH2': 'The whole villa, just for you',
    'priv.inc1': 'Full exclusivity of the villa and its outdoor spaces (patio, garden, pool, olive grove)',
    'priv.inc2': 'All 9 suites with private bathroom',
    'priv.inc3': 'The fully equipped kitchen, usable by your own caterer or our partner chef',
    'priv.inc4': 'Access to the 4-hectare olive grove for your outdoor activities',
    'priv.inc5': 'Secure parking and a dedicated on-site contact',
    'priv.options': 'Optional: full or half board with a private chef, Koroneiki olive oil tasting workshop, airport transfers (Tunis-Carthage / Enfidha-Hammamet), Cap Bon excursions, local guest experts.',
    'priv.pricingKicker': 'Packages & Rates',
    'priv.pricingH2': 'Base rate: 2,600 TND per night (≈ €765)',
    'priv.tier1h': 'Discovery',
    'priv.tier1nights': '3 to 4 nights',
    'priv.tier1price': '/ night (≈ €765)',
    'priv.tier1desc': 'Accommodation + breakfast',
    'priv.tier2h': 'Immersion',
    'priv.tier2nights': '5 to 6 nights · −10%',
    'priv.tier2price': '/ night (≈ €690)',
    'priv.tier2desc': 'Accommodation + breakfast, easy access to estate activities',
    'priv.tier3h': 'Extended Stay',
    'priv.tier3nights': '7 nights and more · −15%',
    'priv.tier3price': '/ night (≈ €650)',
    'priv.tier3desc': 'Best suited for retreats and olive-oil themed stays; full board available',
    'priv.restauration': '30% deposit at booking; 3-night minimum for any privatization. Optional catering: half board 100 to 120 TND/person/night, full board with on-site chef 150 to 180 TND/person/night.',
    'priv.faqKicker': 'Frequently Asked Questions',
    'priv.faqH2': 'Everything about privatization',
    'priv.faq1q': 'What is the minimum number of participants to privatize the villa?',
    'priv.faq1a': 'Privatization is available from 10 participants, up to 25 people for accommodation. For smaller groups, contact us — a solution can be arranged.',
    'priv.faq2q': 'Can we hold yoga classes, workshops or activities in the garden or olive grove?',
    'priv.faq2a': 'Yes, the garden, patio and olive grove are freely accessible for your sessions and activities. We can also connect your group with local practitioners (yoga, Tunisian cooking, crafts, olive oil tasting).',
    'priv.faq3q': 'Is catering available on site?',
    'priv.faq3a': 'The kitchen is fully equipped and can be used by your own caterer or chef. We also offer, as an option, a partner chef for full or half board, as well as Koroneiki olive oil tasting workshops from the estate.',
    'priv.faq4q': 'What is the best time for an olive-oil themed stay?',
    'priv.faq4a': 'The olive harvest runs from mid-October to the end of January — this is also our low season, ideal for privatizing the villa at favorable rates.',
    'priv.faq5q': 'Do you offer airport transfers?',
    'priv.faq5a': 'Yes, as an option, from Tunis-Carthage and Enfidha-Hammamet airports.',
    'priv.finalCta': 'Request a Privatization Quote',
    'huile.logoAlt': 'Domaine Dar Aïcha logo - Tazarka, Tunisia',
    'huile.kicker': 'Our Brand',
    'huile.h2': 'Domaine Dar Aïcha — Extra Virgin Olive Oil',
    'huile.lede': 'Born from our 4 hectares of Koroneiki olive trees in Tazarka, our extra virgin olive oil is hand-picked and cold-pressed to preserve the full richness of its aromas. 2024 vintage, packaged in 500ml and 250ml bottles under our own brand.',
    'huile.imgAlt1': 'Bottles of Domaine Dar Aïcha olive oil, 250ml and 500ml formats, at sunset on the Tazarka estate',
    'huile.kicker2': 'An Exceptional Oil',
    'huile.h2b': 'A premium product, from field to bottle',
    'huile.li1': 'Extra virgin olive oil, Koroneiki variety',
    'huile.li2': 'First cold pressing, hand-picked',
    'huile.li3': '2024 vintage — available in 500ml and 250ml',
    'huile.li4': 'Produced and bottled in Tunisia',
    'huile.cta1': 'Order Our Olive Oil',
    'huile.kicker3': 'Terroir & Production',
    'huile.h2c': '4 hectares of Koroneiki olive trees facing the sea',
    'huile.p2': 'On our agricultural estate in Tazarka, a Koroneiki olive grove — a Greek cultivar renowned for its fine, aromatic oil — stretches between the estate and the coastline. A family production, crafted for a distinctive extra virgin olive oil.',
    'huile.li5': 'Koroneiki variety, renowned for its aromatic richness',
    'huile.li6': '4 hectares cultivated on the Tazarka estate',
    'huile.li7': 'Harvest and pressing overseen by the family',
    'huile.kicker4': 'From Olive Tree to Bottle',
    'huile.h2d': 'Our Process',
    'huile.step1h': 'Cultivation',
    'huile.step1p': 'Year-round care of the Koroneiki olive trees on our 4 hectares facing the sea.',
    'huile.step2h': 'Harvest',
    'huile.step2p': 'Olives picked at peak ripeness to preserve their aromas.',
    'huile.step3h': 'Pressing',
    'huile.step3p': 'Cold extraction for a high-quality extra virgin oil.',
    'huile.step4h': 'Bottling',
    'huile.step4p': 'Carefully packaged under our own brand, available on request from the estate.',
    'huile.kicker5': 'Domaine Dar Aïcha in Pictures',
    'huile.h2e': 'Our Oil, Showcased',
    'huile.videoAria': 'Presentation video of the Domaine Dar Aïcha olive oil range, 500ml and 250ml formats',
    'huile.img2': 'Domaine Dar Aïcha olive oil served at the table with a tomato and mozzarella salad',
    'region.kicker': 'The Property & the Region',
    'region.h2': 'Tazarka, between Cap Bon beaches and Nabeul countryside',
    'region.lede': 'The property spans 4 hectares in Tazarka, near the beaches of Maamoura and Nabeul, in the Nabeul governorate (Cap Bon).',
    'region.img1': 'Aerial view of the 4-hectare property in Tazarka with the villa, olive grove and gardens',
    'region.img2': 'Back garden of the property overlooking the olive grove and coastline',
    'region.img3': 'Mediterranean gardens at the Dar Aïcha property',
    'region.img4': 'Palm-lined driveway leading to the villa',
    'region.img6': 'Fine sandy beach and turquoise waters near Tazarka',
    'avis.kicker': 'Reviews & Testimonials',
    'avis.h2': 'The trust of our travelers',
    'avis.r1': 'Airbnb · Superhost',
    'avis.r2': 'Vrbo — "Wonderful"',
    'avis.r3': 'Abritel — "Wonderful"',
    'avis.disclaimer1': 'Ratings verified by booking platforms, viewable directly on',
    'avis.disclaimer2': 'and',
    'reserver.kicker': 'Book',
    'reserver.h2': 'Request a Quote or Check Availability',
    'reserver.labelNom': 'Full Name',
    'reserver.labelArrivee': 'Arrival Date',
    'reserver.labelDepart': 'Departure Date',
    'reserver.labelVoyageurs': 'Number of Guests',
    'reserver.labelType': 'Request Type',
    'reserver.opt1': 'Stay / Seasonal Rental',
    'reserver.opt2': 'Guesthouse (one suite)',
    'reserver.opt3': 'Event / Reception',
    'reserver.opt4': 'Privatization / Group Stay',
    'reserver.opt5': 'Koroneiki Olive Oil',
    'reserver.labelMessage': 'Your Message',
    'reserver.submit': 'Send via WhatsApp',
    'reserver.coordH3': 'Contact Details',
    'reserver.contact1': 'Reservations (Fatma, house host):',
    'reserver.contact3': 'Tazarka, Korba, Nabeul Governorate, Tunisia',
    'contact.kicker': 'Find Us',
    'contact.h2': 'Tazarka, Korba — Nabeul Governorate',
    'contact.mapTitle': 'Location of Dar Aïcha in Tazarka, Korba, Tunisia',
    'footer.blurb': 'A 9-suite villa, Koroneiki olive grove and private events in Tazarka, Cap Bon, Tunisia.',
    'footer.explorerH4': 'Explore',
    'footer.infosH4': 'Information',
    'footer.contactH4': 'Contact',
    'footer.copyright2': 'Dar Aïcha Tazarka. All rights reserved.',
    'footer.credit': 'Site designed for Dar Aïcha — Mohcen Ben Amara',
    'whatsapp.aria': 'Contact Dar Aïcha on WhatsApp',
    'lightbox.closeAria': 'Close',
    'homeMore.villa': 'Discover the villa and its 9 suites in detail',
    'homeMore.espaces': 'Explore all our living spaces',
    'homeMore.sejourner': 'Everything about seasonal rental in Cap Bon',
    'homeMore.evenements': 'Plan your wedding or event in Tazarka',
    'homeMore.huile': 'Discover our Koroneiki olive oil',
    'homeMore.region': 'Discover the Cap Bon region',
    'breadcrumb.home': 'Home',
    'footer.copyright1': '©',
    'villaPage.breadcrumb': 'The Villa & Suites',
    'villaPage.badge1': '9 en-suite bedrooms',
    'villaPage.badge2': 'Contemporary Tunisian architecture',
    'villaPage.badge3': 'Infinity pool',
    'villaPage.h1': 'The Villa & its 9 Suites',
    'villaPage.lede': 'Discover Dar Aïcha\'s architecture and its 9 individually decorated en-suite bedrooms, between contemporary lines, local stone and traditional Tunisian craftsmanship.',
    'villaPage.cta1': 'Check Availability',
    'villaPage.archKicker': 'Architecture',
    'villaPage.archH2': 'A contemporary villa rooted in local craftsmanship',
    'villaPage.archLede': 'Dar Aïcha combines clean, contemporary lines with local stone, an engraved pediment and Mediterranean gardens — a villa designed to host families and events on a 4-hectare property in Tazarka.',
    'villaPage.img1': 'Facade of Villa Dar Aïcha, contemporary white architecture with local stone and Mediterranean garden',
    'villaPage.img2': 'Entrance driveway of Villa Dar Aïcha lined with palm trees',
    'villaPage.img3': 'Engraved pediment above the entrance of Villa Dar Aïcha',
    'villaPage.img4': 'Facade of the villa illuminated at night',
    'villaPage.img5': 'Aerial view of the Dar Aïcha property, villa surrounded by gardens and olive trees',
    'villaPage.img6': 'Outdoor stone staircase leading to the upstairs suites',
    'villaPage.img7': 'Entrance arch of Villa Dar Aïcha, carved golden stone',
    'villaPage.img8': 'Mediterranean garden bordering the villa\'s facade',
    'villaPage.suitesKicker': '9 Suites',
    'villaPage.suitesH2': 'Individually decorated en-suite bedrooms',
    'villaPage.suitesLede': 'Each of the 9 suites has its own decor blending contemporary comfort with traditional Tunisian craftsmanship, plus a private bathroom.',
    'villaPage.priceUnit': 'per night',
    'villaPage.suite1h': 'Suite Yasmine',
    'villaPage.suite1img': 'Suite Yasmine with double bed and traditional Tunisian décor',
    'villaPage.suite1p': 'A bright suite with private bathroom, decorated with ceramics and local craftsmanship.',
    'villaPage.suite2h': 'Suite Zeitoun',
    'villaPage.suite2img': 'Suite Zeitoun, olive-tree themed décor and private bathroom',
    'villaPage.suite2p': 'Named after the olive tree, this suite opens onto the gardens and offers a private bathroom.',
    'villaPage.suite3h': 'Suite Jasmin',
    'villaPage.suite3img': 'Suite Jasmin with traditional bed linens and private bathroom',
    'villaPage.suite3p': 'A cosy suite with traditional textiles and a private bathroom.',
    'villaPage.suite4h': 'Suite Nour',
    'villaPage.suite4img': 'Suite Nour, bright bedroom with private bathroom',
    'villaPage.suite4p': 'A bright, restful suite with a private bathroom.',
    'villaPage.suite5h': 'Suite Amel',
    'villaPage.suite5img': 'Suite Amel with private bathroom and traditional décor',
    'villaPage.suite5p': 'A calm suite decorated with local craftsmanship, with a private bathroom.',
    'villaPage.suite6h': 'Suite Hssin',
    'villaPage.suite6img': 'Suite Hssin with double bed and traditional Tunisian décor',
    'villaPage.suite6p': 'A double bedroom with private bathroom, decorated in traditional Tunisian style.',
    'villaPage.suite7h': 'Suite Salma',
    'villaPage.suite7img': 'Suite Salma, bedroom with private bathroom',
    'villaPage.suite7p': 'A comfortable suite with private bathroom, ideal for a couple.',
    'villaPage.suite8h': 'Suite Rym',
    'villaPage.suite8img': 'Suite Rym with private bathroom and local decorative details',
    'villaPage.suite8p': 'A quiet suite with a private bathroom and traditional decorative details.',
    'villaPage.suite9h': 'Suite Farah',
    'villaPage.suite9img': 'Suite Farah, bedroom with private bathroom',
    'villaPage.suite9p': 'The ninth suite, with private bathroom, completes the villa’s 9-bedroom capacity.',
    'villaPage.amKicker': 'Bedroom amenities',
    'villaPage.amH2': 'Comfort in every suite',
    'villaPage.am1': 'Private bathroom in every suite',
    'villaPage.am2': 'Air conditioning',
    'villaPage.am3': 'Fresh bed linens',
    'villaPage.am4': 'Individual decor with local craftsmanship',
    'villaPage.am5': 'Access to shared living spaces',
    'villaPage.am6': 'Garden or pool view depending on suite',
    'villaPage.am7': 'Housekeeping during your stay',
    'villaPage.am8': 'Personalised welcome by Fatma, house host',
    'villaPage.diningKicker': 'Dining room',
    'villaPage.diningH2': 'A dining room for shared meals',
    'villaPage.diningP': 'The villa’s dining room comfortably seats guests for shared meals, between family gatherings and private events.',
    'villaPage.diningImg': 'Dining room of Villa Dar Aïcha set for a shared meal',
    'villaPage.salonKicker': 'Living rooms',
    'villaPage.salonH2': 'Majlis-style living rooms',
    'villaPage.salonP': 'Low seating, Berber cushions and traditional rugs: the villa’s living rooms reflect the codes of the Tunisois majlis for relaxed evenings.',
    'villaPage.salonImg': 'Majlis-style living room with low seating and Berber cushions',
    'villaPage.salonLink': 'Discover our other spaces',
    'villaPage.info1h': 'Capacity',
    'villaPage.info1p': '9 suites, up to 18-20 guests in guesthouse mode, or up to 25 guests for a full private rental.',
    'villaPage.info2h': 'Contact & arrival',
    'villaPage.info2p': 'Check-in from 3pm, check-out at 11am. On-site contact: Fatma, house host.',
    'villaPage.info3h': 'Location',
    'villaPage.info3p': 'Villa Dar Aïcha, Tazarka, Korba, Nabeul Governorate, Cap Bon, Tunisia.',
    'villaPage.ctaKicker': 'Book',
    'villaPage.ctaH2': 'Ready to discover Dar Aïcha?',
    'villaPage.ctaLede': 'Check availability for a suite or the whole villa, depending on the season.',
    'villaPage.cta2': 'Request a Quote',
    'espacesPage.breadcrumb': 'Our Spaces',
    'espacesPage.badge1': 'Outdoor kitchen & BBQ bar',
    'espacesPage.badge2': 'Majlis living rooms',
    'espacesPage.badge3': 'Zellige-tiled patio',
    'espacesPage.h1': 'Our Spaces: Kitchen, Living Rooms, Patio & Play Area',
    'espacesPage.lede': 'Beyond the 9 suites, Dar Aïcha is also about its shared spaces — the outdoor kitchen with BBQ bar, the indoor kitchen, majlis-style living rooms, the zellige-tiled fountain patio and a swing corner for children.',
    'espacesPage.cta1': 'Request a Quote',
    'espacesPage.k1': 'Outdoor kitchen & BBQ bar',
    'espacesPage.h2_1': 'The perfect spot for al fresco meals',
    'espacesPage.p1': 'Marble bar counter, matching outdoor table, and a barbecue corner sheltered behind a wrought-iron screen: the outdoor kitchen extends the patio for grilling, drinks and family meals facing the olive grove.',
    'espacesPage.li1': 'Marble bar and matching outdoor table',
    'espacesPage.li2': 'Fully equipped barbecue corner, sink and storage',
    'espacesPage.li3': 'Open view over the countryside and olive grove',
    'espacesPage.img1': 'Outdoor kitchen with marble bar and BBQ corner, view over the Tazarka countryside',
    'espacesPage.img2': 'Barbecue corner of the outdoor kitchen with grill, sink and wooden storage',
    'espacesPage.img3': 'Outdoor kitchen viewed from the bar, wrought-iron screen',
    'espacesPage.k2': 'Indoor kitchen',
    'espacesPage.h2_2': 'A kitchen wide open onto the pool',
    'espacesPage.p2': 'Central granite island, 5-burner range and large glass doors opening onto the terrace and pool: the indoor kitchen is the welcoming heart of the villa, designed for cooking as a family while keeping a view outside.',
    'espacesPage.img4': 'Central granite kitchen island with 5-burner range',
    'espacesPage.img5': 'Indoor kitchen wide open onto the pool and terrace',
    'espacesPage.img6': 'Indoor kitchen of Villa Dar Aïcha, worktop and storage',
    'espacesPage.img7': 'Table set with traditional Tunisian ceramic tableware',
    'espacesPage.k3': 'Majlis-style living rooms',
    'espacesPage.h2_3': 'The art of hosting, Tunisois-style',
    'espacesPage.p3': 'Low seating, colourful Berber cushions and traditional rugs: Dar Aïcha’s living rooms follow the codes of the Tunisois majlis, for convivial evenings between sofas and large glass doors opening onto the patio.',
    'espacesPage.img8': 'Living room opening onto the kitchen through a large glass door',
    'espacesPage.img9': 'Tunisois-style majlis living room with low seating, Berber cushions and large glass doors',
    'espacesPage.img10': 'Living room with beige seating, embroidered cushions and sheer curtains',
    'espacesPage.img11': 'Large living room with colourful Berber rugs and armchairs, marble floor',
    'espacesPage.img12': 'Living room of Villa Dar Aïcha, traditional Tunisian craftsmanship',
    'espacesPage.k4': 'Central patio',
    'espacesPage.h2_4': 'A zellige-tiled fountain at the heart of the villa',
    'espacesPage.p4': 'The vaulted patio distributes the living spaces around a tiered zellige-tiled fountain, in the purest Tunisois tradition. Stone colonnades and a shaded dining corner make it a place to pass through and relax at any time of day.',
    'espacesPage.img13': 'Tiered fountain in the patio, arches lined up towards the sea',
    'espacesPage.img14': 'Vaulted central patio with marble fountain and handcrafted lantern',
    'espacesPage.img15': 'Patio and shaded outdoor dining corner, stone colonnades',
    'espacesPage.img16': 'Indoor patio with Tunisian archway and zellige-tiled fountain',
    'espacesPage.k5': 'Children’s play area',
    'espacesPage.h2_5': 'A swing corner by the pool',
    'espacesPage.p5': 'Designed for families, a play area with swings and a play frame is set up near the pool, among palm trees and gardens — so children can enjoy their stay at Dar Aïcha too.',
    'espacesPage.img17': 'Swing corner for children by the pool, surrounded by palm trees and gardens',
    'espacesPage.img18': 'Swing and play frame for children near the infinity pool',
    'espacesPage.img19': 'Infinity pool of Villa Dar Aïcha with loungers and open view',
    'espacesPage.img20': 'Backyard garden of the property with view over the olive grove and coast',
    'espacesPage.ctaKicker': 'Discover',
    'espacesPage.ctaH2': 'Want to see these spaces for yourself?',
    'espacesPage.ctaLede': 'Explore the villa’s architecture and its 9 suites, or request a quote directly for your stay.',
    'espacesPage.ctaBtn1': 'Discover the Villa',
    'locationPage.breadcrumb': 'Seasonal Rental & Guesthouse',
    'locationPage.badge1': '★ 4.88/5 · Airbnb Superhost',
    'locationPage.badge2': '9.0/10 · Vrbo & Abritel',
    'locationPage.badge3': 'Guesthouse · Cap Bon',
    'locationPage.h1': 'Guesthouse & Seasonal Rental in Cap Bon, Tazarka',
    'locationPage.lede': 'Dar Aïcha can be booked by the suite as a guesthouse throughout the year, or in full for the high season — a 9-suite villa between Nabeul and Korba, in the Cap Bon governorate.',
    'locationPage.cta1': 'Check Availability',
    'locationPage.k1': 'Two ways to stay',
    'locationPage.h2_1': 'Guesthouse in low season, seasonal rental in high season',
    'locationPage.lede2': 'From June to September, Dar Aïcha is booked as an exclusive seasonal rental — the whole villa for your group. In low season, the villa operates as a guesthouse: book one or more suites, with access to the shared spaces.',
    'locationPage.card1h': 'Guesthouse (low season)',
    'locationPage.card1p': 'Booking by the suite, from 255 TND per night (≈ €75). Access to the living rooms, outdoor kitchen, patio and pool.',
    'locationPage.card2h': 'Seasonal rental (high season)',
    'locationPage.card2p': 'Full privatisation of the 9 suites, June to September, up to 25 guests — direct quote-based pricing, no platform commission.',
    'locationPage.card3h': 'Contact & arrival',
    'locationPage.card3p': 'Check-in from 3pm, check-out at 11am. On-site contact: Fatma, house host — ',
    'locationPage.k2': 'Why choose Dar Aïcha',
    'locationPage.h2_2': 'A rare address in Cap Bon',
    'locationPage.img1': 'Infinity pool of Villa Dar Aïcha, serene atmosphere facing the Tazarka countryside',
    'locationPage.p1': 'Unlike a standard hotel, Dar Aïcha offers the privacy of a large private home: 9 air-conditioned suites, generous shared spaces (outdoor kitchen, majlis living rooms, patio), an infinity pool and 4 hectares of gardens and olive grove, just minutes from the beaches of Nabeul and Maamoura.',
    'locationPage.li1': 'Air-conditioned suites with private bathroom',
    'locationPage.li2': 'Infinity pool, gardens and 4-hectare olive grove',
    'locationPage.li3': 'Close to the beaches of Nabeul and Maamoura, in Cap Bon',
    'locationPage.li4': 'Personalised welcome by Fatma, house host',
    'locationPage.link1': 'Discover the villa and its suites',
    'locationPage.k3': 'In pictures',
    'locationPage.h2_3': 'The atmosphere of a stay at Dar Aïcha',
    'locationPage.img2': 'Infinity pool with parasols and view over the Tazarka countryside',
    'locationPage.img3': 'Suite Hssin with double bed and traditional Tunisian décor',
    'locationPage.img4': 'Private bathroom of one of the suites at Villa Dar Aïcha',
    'locationPage.img5': 'Loungers and parasols by the pool at Dar Aïcha',
    'locationPage.img6': 'Wide view of the villa’s facade surrounded by palm trees',
    'locationPage.img7': 'Bathroom with traditional Tunisian blue zellige tiling',
    'locationPage.k4': 'Verified reviews',
    'locationPage.h2_4': 'The trust of our guests',
    'locationPage.rating1': 'Airbnb · Superhost',
    'locationPage.rating2': 'Vrbo — “Wonderful”',
    'locationPage.rating3': 'Abritel — “Wonderful”',
    'locationPage.ctaKicker': 'Book',
    'locationPage.ctaH2': 'Check availability for your stay',
    'locationPage.ctaLede': 'A suite, a group of friends, or the whole villa — describe your project and we’ll get back to you quickly on WhatsApp or by email.',
    'locationPage.ctaBtn': 'Request Availability',
    'evenementsPage.breadcrumb': 'Weddings & Events',
    'evenementsPage.badge1': 'Up to 250 guests',
    'evenementsPage.badge2': 'Pool & 4-hectare gardens',
    'evenementsPage.badge3': 'Tazarka · Cap Bon',
    'evenementsPage.h1': 'Weddings & Private Events in Tazarka, Cap Bon',
    'evenementsPage.lede': 'A 4-hectare property between olive grove and sea to celebrate a wedding, an engagement or a corporate event, for up to 250 guests.',
    'evenementsPage.cta1': 'Request an Event Quote',
    'evenementsPage.k1': 'Capacity & pricing',
    'evenementsPage.h2_1': 'A property designed to host',
    'evenementsPage.lede2': 'From an intimate gathering to a large wedding, Dar Aïcha adapts its spaces — patio, gardens, pool terrace — to the size of your event.',
    'evenementsPage.card1h': 'Up to 250 guests',
    'evenementsPage.card1p': 'Gardens, patio and pool terrace can host a large-scale reception.',
    'evenementsPage.card2h': '3,500 — 5,500 TND',
    'evenementsPage.card2p': 'Rental rate for the event space, depending on the package chosen and the number of guests.',
    'evenementsPage.card3h': 'Custom quote',
    'evenementsPage.card3p': 'Every event is unique: contact us for a quote tailored to your date and format.',
    'evenementsPage.k2': 'Included services',
    'evenementsPage.h2_2': 'A turnkey setting for your reception',
    'evenementsPage.li1': 'Access to the gardens, patio and pool terrace',
    'evenementsPage.li2': 'Private parking on the property',
    'evenementsPage.li3': 'Night-time lighting of the facade and gardens',
    'evenementsPage.li4': 'Option to accommodate close family in the villa’s 9 suites',
    'evenementsPage.li5': 'Coordination with your vendors (caterer, decorator, photographer)',
    'evenementsPage.img1': 'Aerial view of the pool terrace set up for an event at Dar Aïcha',
    'evenementsPage.link1': 'Accommodate your guests in our 9 suites',
    'evenementsPage.k3': 'How it works',
    'evenementsPage.h2_3': 'Book your date in 3 steps',
    'evenementsPage.step1h': 'Contact & visit',
    'evenementsPage.step1p': 'Describe your project (date, number of guests, package wanted) and visit the property if possible.',
    'evenementsPage.step2h': 'Quote & confirmation',
    'evenementsPage.step2p': 'We prepare a custom quote and lock in your date once confirmed.',
    'evenementsPage.step3h': 'The big day',
    'evenementsPage.step3p': 'We prepare the spaces for your guests’ arrival and remain available throughout the event.',
    'evenementsPage.k4': 'In pictures',
    'evenementsPage.h2_4': 'Receptions with a Mediterranean décor',
    'evenementsPage.img2': 'Pool terrace set up with hanging parasols for a reception',
    'evenementsPage.img3': 'Poolside loggia set up for a private event',
    'evenementsPage.img4': 'Floral wedding décor on a backdrop of Tunisian ceramics',
    'evenementsPage.img5': 'Facade of Villa Dar Aïcha lit up for a night-time reception',
    'evenementsPage.img6': 'Wedding reception by the pool at Dar Aïcha',
    'evenementsPage.ctaKicker': 'Your event',
    'evenementsPage.ctaH2': 'Request your event quote',
    'evenementsPage.ctaLede': 'Wedding, engagement, birthday or corporate event — tell us about your project and the date you have in mind.',
    'huilePage.breadcrumb': 'Koroneiki Olive Oil',
    'huilePage.badge1': 'Koroneiki variety',
    'huilePage.badge2': '4 hectares · Tazarka',
    'huilePage.badge3': '2024 vintage',
    'huilePage.h1': 'Koroneiki Olive Oil from Domaine Dar Aïcha, Tazarka',
    'huilePage.lede': 'On the 4 hectares of the family property, we grow the Greek Koroneiki variety and produce a fine, fruity, slightly peppery oil, from the field to the bottle.',
    'huilePage.cta1': 'Contact Us to Order',
    'huilePage.k1': 'The terroir',
    'huilePage.h2_1': '4 hectares dedicated to the Koroneiki variety',
    'huilePage.img1': 'Panoramic view of the Koroneiki olive grove on the Tazarka agricultural property',
    'huilePage.p1': 'Chosen for its hardiness and the quality of its oil, Koroneiki — a Greek variety widely planted across the Mediterranean — thrives on our Tazarka property, between the coastal climate of Cap Bon and soil well suited to olive trees.',
    'huilePage.p2': 'Every step, from growing to bottling, is overseen on site to preserve the quality of the fruit.',
    'huilePage.k2': 'Our know-how',
    'huilePage.h2_2': 'From olive grove to bottle',
    'huilePage.step1h': 'Growing',
    'huilePage.step1p': 'Koroneiki olive trees grown on the property’s 4 hectares in Tazarka, with careful year-round maintenance.',
    'huilePage.step2h': 'Harvest',
    'huilePage.step2p': 'Olives harvested at the optimal ripeness to preserve fruity aromas and the quality of the oil.',
    'huilePage.step3h': 'Pressing',
    'huilePage.step3p': 'Cold pressing carried out quickly after the harvest, to preserve the oil’s organoleptic qualities.',
    'huilePage.step4h': 'Bottling',
    'huilePage.step4p': 'Packaged in 500ml and 250ml bottles, kept away from light, to preserve the product’s freshness.',
    'huilePage.k3': 'Our oil',
    'huilePage.h2_3': 'A fine, fruity, slightly peppery oil',
    'huilePage.img2': 'Close-up of a Koroneiki olive oil bottle from Domaine Dar Aïcha',
    'huilePage.p3': 'Domaine Dar Aïcha’s Koroneiki olive oil, 2024 vintage, stands out for its aromatic finesse and slight peppery kick on the finish — typical of this variety. Available in 500ml bottles (9 TND) and 250ml bottles (5 TND).',
    'huilePage.li1': 'Koroneiki variety, harvested and pressed on the property',
    'huilePage.li2': '2024 vintage',
    'huilePage.li3': '500ml bottles (9 TND) and 250ml bottles (5 TND)',
    'huilePage.k4': 'In pictures',
    'huilePage.h2_4': 'Domaine Dar Aïcha, from the field to the finished product',
    'huilePage.img3': 'Bottle of Domaine Dar Aïcha olive oil displayed on a set table',
    'huilePage.img4': 'Logo of Domaine Dar Aïcha, Koroneiki olive oil',
    'huilePage.img5': 'Rows of Koroneiki olive trees on the Tazarka property',
    'huilePage.ctaKicker': 'Order',
    'huilePage.ctaH2': 'Want to taste our Koroneiki olive oil?',
    'huilePage.ctaLede': 'Contact us to find out availability and ordering details for Domaine Dar Aïcha’s oil.',
    'huilePage.cta2': 'Contact Us',
    'regionPage.breadcrumb': 'Property & Region',
    'regionPage.badge1': 'Tazarka · Korba · Nabeul',
    'regionPage.badge2': 'Nabeul Governorate',
    'regionPage.badge3': 'Cap Bon, Tunisia',
    'regionPage.h1': 'Tazarka, at the Heart of Cap Bon',
    'regionPage.lede': 'Between Korba and Nabeul, just minutes from sandy beaches, Dar Aïcha enjoys a prime location in the Nabeul Governorate, also known as Cap Bon.',
    'regionPage.k1': 'Location',
    'regionPage.h2_1': 'Tazarka, a coastal village in Cap Bon',
    'regionPage.img1': 'Outdoor view of the Dar Aïcha property in Tazarka, between gardens and the Cap Bon countryside',
    'regionPage.p1a': 'Tazarka sits on a hillside, about twenty kilometres north of Nabeul, in an area known for its long sandy beaches (',
    'regionPage.p1b': '). The village administratively belongs to the delegation of Korba, in the Nabeul Governorate — the region historically known as “Cap Bon,” which also includes Hammamet, Kelibia, Menzel Temime, Soliman and the ancient site of Kerkouane, a UNESCO World Heritage Site (',
    'regionPage.p1c': ').',
    'regionPage.k2': 'Access',
    'regionPage.h2_2': 'How to reach Dar Aïcha',
    'regionPage.lede2': 'The property is accessible from the two main airports in north-eastern Tunisia.',
    'regionPage.card1h': 'Tunis-Carthage Airport',
    'regionPage.card1p': 'About 75 to 85 km, or 1h15 to 1h30 by road to Tazarka (',
    'regionPage.pClose': ').',
    'regionPage.card2h': 'Enfidha-Hammamet Airport',
    'regionPage.card2p': 'About 50 to 55 km from Nabeul, or roughly 40 minutes by road (',
    'regionPage.card3h': 'Nabeul',
    'regionPage.card3p': 'Capital of the governorate, about twenty kilometres from Tazarka, with its large market and pottery workshops.',
    'regionPage.k3': 'Things to discover',
    'regionPage.h2_3': 'Cap Bon, between sea, craftsmanship and heritage',
    'regionPage.card4h': 'Nabeul & its pottery',
    'regionPage.card4p': 'About 20 km away, Nabeul is known for its market and traditional ceramics and pottery workshops, roughly 1 hour from Tunis-Carthage Airport (',
    'regionPage.card5h': 'Hammamet',
    'regionPage.card5p': 'Cap Bon’s historic seaside resort, its medina and beaches lie just a few kilometres south of Nabeul (',
    'regionPage.card6h': 'Kelibia & Kerkouane',
    'regionPage.card6p': 'Further north, Kelibia (about 55 km from Nabeul) and the ancient Punic site of Kerkouane, a UNESCO World Heritage Site, round out the discovery of Cap Bon (',
    'regionPage.k4': 'Our property',
    'regionPage.h2_4': '4 hectares between olive grove, gardens and villa',
    'regionPage.img2': 'Aerial view of the Dar Aïcha property in Tazarka, villa surrounded by gardens and olive trees',
    'regionPage.img3': 'Palm tree-lined driveway leading to Villa Dar Aïcha',
    'regionPage.img4': 'Outdoor view of the property with Mediterranean gardens',
    'regionPage.img5': 'Backyard garden of the property facing the olive grove and coast',
    'regionPage.k5': 'Location',
    'regionPage.h2_5': 'Tazarka, Korba, Nabeul Governorate',
    'regionPage.ctaKicker': 'Join Us',
    'regionPage.ctaH2': 'Ready to discover Cap Bon from Dar Aïcha?',
    'regionPage.ctaLede': 'A stay, a private reception, or simply a visit to the property — contact us to arrange your visit.',
    'regionPage.cta1': 'Contact Us',
    'nav.maisonHotes': 'Guest House',
    'nav.groupes': 'Groups & Retreats',
    'nav.galerie': 'Gallery',
    'nav.faq': 'FAQ',
    'nav.conditions': 'Stay Conditions',
    'nav.mentions': 'Legal Notice',
    'nav.devis': 'Request a Quote',
    'footer.pagesH4': 'Our Universe',
    'footer.tagline': 'A charming estate on Cap Bon: villa, guest house, private events and Koroneiki olive oil.',
    'contactPage.breadcrumb': 'Contact & Quote',
    'contactPage.badge1': 'Fast response',
    'contactPage.badge2': 'WhatsApp or email',
    'contactPage.badge3': 'Tazarka · Cap Bon',
    'contactPage.h1': 'Let\'s talk about your stay or your event',
    'contactPage.lede': 'Tell us your dates, the number of guests and your project. We will reply with a tailored proposal.',
    'contactPage.k1': 'Your request',
    'contactPage.h2_1': 'Tell us about your project',
    'contactPage.lede2': 'A suite stay, a full villa rental, a group, a retreat or a wedding — one form for every kind of request.',
    'contactPage.labelNom': 'Full name',
    'contactPage.labelEmail': 'Email',
    'contactPage.labelTelephone': 'Phone / WhatsApp',
    'contactPage.labelDates': 'Preferred dates',
    'contactPage.placeholderDates': 'e.g. July 12 to 19, 2027',
    'contactPage.labelPersonnes': 'Number of guests',
    'contactPage.labelType': 'Type of request',
    'contactPage.opt1': 'Villa',
    'contactPage.opt2': 'Guest house',
    'contactPage.opt3': 'Group or retreat',
    'contactPage.opt4': 'Wedding or event',
    'contactPage.opt5': 'Other',
    'contactPage.labelMessage': 'Your message',
    'contactPage.submit': 'Send my request',
    'contactPage.rgpd': 'The information you send is used only to respond to your request.',
    'contactPage.successMsg': 'Thank you, your request has been received. We will get back to you shortly.',
    'contactPage.coordH3': 'Another way to reach us',
    'contactPage.coordLede': 'Prefer a direct message? Choose the channel that suits you.',
    'contactPage.ctaWhatsapp': 'Message us on WhatsApp',
    'contactPage.contactAccueil': 'On-site host (Fatma):',
    'contactPage.k2': 'Before you write',
    'contactPage.h2_2': 'Discover our universe first',
    'contactPage.link1h': 'The villa',
    'contactPage.link1p': '9 suites, an infinity pool and gardens set on 4 hectares.',
    'contactPage.link1a': 'Discover the villa',
    'contactPage.link2h': 'Weddings & events',
    'contactPage.link2p': 'Private receptions with a custom quote, in a Mediterranean setting.',
    'contactPage.link2a': 'See our events',
    'contactPage.link3h': 'Groups & retreats',
    'contactPage.link3p': 'Off-season full privatization, with tiered pricing by length of stay.',
    'contactPage.link3a': 'See the group offer',
    'faqPage.breadcrumb': 'Frequently Asked Questions',
    'faqPage.badge1': 'Capacity & rates',
    'faqPage.badge2': 'Booking & stay',
    'faqPage.badge3': 'Tazarka · Cap Bon',
    'faqPage.h1': 'Frequently asked questions about Dar Aïcha',
    'faqPage.lede': 'Capacity, rates, arrival and departure, cancellation, pets, transfers: answers to the questions most often asked before a stay or an event.',
    'faqPage.k1': 'FAQ',
    'faqPage.h2_1': 'All your questions before booking',
    'faqPage.lede2': 'Can\'t find your answer? Write to us directly, we reply quickly by WhatsApp or email.',
    'faqPage.q1': 'What is the exact capacity of the villa?',
    'faqPage.a1': 'The villa has 9 air-conditioned suites with private bathrooms, with a standard capacity of up to 18 adults, and up to 25 people depending on configuration and extra bedding. It is also possible to book a single suite in the guest house rather than the entire villa.',
    'faqPage.q2': 'What is the difference between high-season seasonal rental and low-season guest house?',
    'faqPage.a2': 'In high season, the entire villa is available for private rental on a custom quote, for up to 25 people. Outside high season, you can book a single suite in the guest house, starting at 255 TND/night, breakfast included. A group or retreat package with full privatization is also available outside the season, at tiered rates depending on the length of stay.',
    'faqPage.q3': 'What is included when privatizing the villa?',
    'faqPage.a3': 'Privatization gives access to the 9 suites, the living rooms, the infinity pool, the patio, the gardens and the 4-hectare olive grove. The exact details of services (catering, additional services) are specified in the quote for your project.',
    'faqPage.q4': 'What are your rates?',
    'faqPage.a4': 'A suite in the guest house starts at 255 TND/night, breakfast included, outside high season. Renting the entire villa in high season is by custom quote. For a group or retreat stay outside the season, the rate is tiered: 2600 TND/night for 1 to 2 nights, 2340 TND/night for 3 to 5 nights, 2210 TND/night from 6 nights onward, for the entire villa for up to 20 guests with breakfast included, plus 120 TND/night per extra guest up to 25. Optional catering ranges from 100 to 180 TND per person per night depending on the package. A 30% deposit is required at booking, for a minimum stay of 3 nights.',
    'faqPage.q5': 'What are the check-in and check-out times?',
    'faqPage.a5': 'Check-in is from 3pm and check-out is before 11am. Fatma, present on site, welcomes you and remains available during your stay.',
    'faqPage.q6': 'What is your cancellation policy?',
    'faqPage.a6': 'Cancellation terms are specified when your booking is confirmed, depending on the type of stay or event.',
    'faqPage.q7': 'Are pets allowed?',
    'faqPage.a7': 'This should be requested at the time of booking, so we can confirm depending on the period and type of stay.',
    'faqPage.q8': 'Is there parking on site?',
    'faqPage.a8': 'Yes, the property has private parking for guests and for events hosted on site.',
    'faqPage.q9': 'How do I get to Tazarka from the airport?',
    'faqPage.a9': 'Tunis-Carthage and Enfidha-Hammamet are the two most convenient airports for reaching Tazarka; driving time depends on traffic conditions. Feel free to ask us for advice on planning your trip.',
    'faqPage.q10': 'Can a wedding or event be organized at Dar Aïcha?',
    'faqPage.a10': 'Yes, the property hosts weddings and private receptions starting at 3,500 TND, with a custom quote depending on the season and package chosen. Capacity can go up to 250 guests only if the event package and required permits allow it; vendors (catering, decoration, photography) are coordinated upon confirmation.',
    'faqPage.q11': 'Can you stay at Dar Aïcha outside the tourist season?',
    'faqPage.a11': 'Yes, outside high season the property operates as a guest house (booking by suite) or as a full privatization for groups and retreats, at tiered rates depending on the length of stay.',
    'faqPage.q12': 'Can I buy the property\'s Koroneiki olive oil?',
    'faqPage.a12': 'The property produces Koroneiki olive oil from its 4 hectares of olive groves, under the Domaine Dar Aïcha brand. Contact us for availability and purchase details.',
    'faqPage.q13': 'Are the suites air-conditioned? Is there Wifi?',
    'faqPage.a13': 'All 9 suites are air-conditioned. Wifi availability is to be confirmed at the time of booking.',
    'faqPage.q14': 'How do I contact you for a quote?',
    'faqPage.a14': 'The simplest way is to write to us on WhatsApp or fill out our contact form, specifying your dates, number of guests and your project.',
    'faqPage.cta1': 'Request a quote',
    'conditionsPage.breadcrumb': 'Stay Conditions',
    'conditionsPage.badge1': 'Check-in 3pm · Check-out 11am',
    'conditionsPage.badge2': 'Deposit at booking',
    'conditionsPage.badge3': 'Tazarka · Cap Bon',
    'conditionsPage.h1': 'Stay conditions at Dar Aïcha',
    'conditionsPage.lede': 'Practical information to know before you arrive: schedule, booking, cancellation, house rules and liability.',
    'conditionsPage.k1': 'Schedule',
    'conditionsPage.h2_1': 'Check-in and check-out',
    'conditionsPage.p1': 'Check-in is from 3pm and check-out is before 11am. Please contact Fatma, on site, or the property\'s WhatsApp number before you arrive, to coordinate your arrival time.',
    'conditionsPage.k2': 'Booking',
    'conditionsPage.h2_2': 'Booking and deposit',
    'conditionsPage.p2': 'For group or retreat privatizations, a 30% deposit is required at booking. For a standard seasonal rental or a guest house suite, a deposit is required at confirmation, specified in the quote.',
    'conditionsPage.k3': 'Cancellation',
    'conditionsPage.h2_3': 'Cancellation terms',
    'conditionsPage.p3': 'Cancellation terms are communicated with each quote, depending on the type of stay or event and the period concerned.',
    'conditionsPage.k4': 'On site',
    'conditionsPage.h2_4': 'House rules',
    'conditionsPage.rule1': 'No unannounced party is allowed without prior agreement with the property.',
    'conditionsPage.rule2': 'Respect for the neighbourhood is required at all times during the stay.',
    'conditionsPage.rule3': 'Pets are welcome upon request, to be confirmed at the time of booking.',
    'conditionsPage.rule4': 'The maximum capacity stated in the quote must be respected throughout the stay.',
    'conditionsPage.k5': 'Receptions',
    'conditionsPage.h2_5': 'Events and receptions',
    'conditionsPage.p5': 'Any reception, wedding or private event requires prior authorization from the property and is organized within the framework of the corresponding event quote, including the number of guests and planned vendors.',
    'conditionsPage.k6': 'Liability',
    'conditionsPage.h2_6': 'Liability',
    'conditionsPage.p6': 'Any material damage found during the stay is the responsibility of the tenant or event organizer. Every guest is asked to treat the premises, furniture and outdoor areas with the same care as a private home.',
    'conditionsPage.closing': 'For any question about these conditions before booking, contact us directly.',
    'conditionsPage.cta1': 'Request a quote',
    'mentionsPage.breadcrumb': 'Legal Notice',
    'mentionsPage.badge1': 'Site publisher',
    'mentionsPage.badge2': 'GDPR & privacy',
    'mentionsPage.badge3': 'Tazarka · Cap Bon',
    'mentionsPage.h1': 'Legal notice & privacy',
    'mentionsPage.lede': 'Information about the site publisher, hosting, intellectual property and the handling of your personal data.',
    'mentionsPage.k1': 'Publisher',
    'mentionsPage.h2_1': 'Site publisher',
    'mentionsPage.p1': 'This site is published by Dar Aïcha Tazarka, Route de Sooma, 8020 Tazarka, Nabeul Governorate, Tunisia. Contact: daraichatazarka@gmail.com. Registration details available on request.',
    'mentionsPage.k2': 'Hosting',
    'mentionsPage.h2_2': 'Site hosting',
    'mentionsPage.p2': 'The site is hosted by a professional web hosting provider.',
    'mentionsPage.k3': 'Intellectual property',
    'mentionsPage.h2_3': 'Intellectual property',
    'mentionsPage.p3': 'All photographs, text and content on this site are the property of Dar Aïcha Tazarka and are protected. Any reproduction, in whole or in part, is prohibited without prior authorization.',
    'mentionsPage.k4': 'Privacy',
    'mentionsPage.h2_4': 'Privacy policy (GDPR)',
    'mentionsPage.p4': 'Data submitted through the contact form is used only to respond to your request. It is not shared with third parties and is kept for as long as necessary to process your request. You may request deletion of your data at any time by writing to daraichatazarka@gmail.com.',
    'mentionsPage.k5': 'Cookies',
    'mentionsPage.h2_5': 'Cookies',
    'mentionsPage.p5': 'This site does not use third-party tracking cookies. Only local preferences, such as display language or light/dark theme, are stored locally in your browser.',
    'mentionsPage.closing': 'For any question about this legal notice, contact us directly.',
    'mentionsPage.cta1': 'Contact us',
    'maisonHotesPage.breadcrumb': 'Guest House',
    'maisonHotesPage.badge1': 'From 255 TND/night',
    'maisonHotesPage.badge2': 'Breakfast included',
    'maisonHotesPage.badge3': 'Tazarka · Cap Bon',
    'maisonHotesPage.h1': 'Dar Aïcha, a guest house on Cap Bon',
    'maisonHotesPage.lede': 'Outside the high tourist season, Villa Dar Aïcha operates as a guest house: individual rooms and suites for travellers, families or small groups, set in a working farm and Mediterranean landscape.',
    'maisonHotesPage.cta1': 'Request a quote',
    'maisonHotesPage.cta2': 'See the suites',
    'maisonHotesPage.k1': 'The guest house experience',
    'maisonHotesPage.h2_1': 'A convivial stay, room by room',
    'maisonHotesPage.lede2': 'On its 4-hectare farm planted with Koroneiki olive trees, Dar Aïcha offers two ways to stay depending on the season. During the high tourist season, the whole villa is rented to a single group. Outside the high season, the 9 suites open up for individual booking: this is the guest house formula, with personal hospitality from Fatma and access to the shared spaces.',
    'maisonHotesPage.card1h': 'Family atmosphere',
    'maisonHotesPage.card1p': 'Personal hospitality on site, on a working farm where olive trees have been grown for several generations.',
    'maisonHotesPage.card2h': 'A farm and Mediterranean setting',
    'maisonHotesPage.card2p': 'Gardens, a 4-hectare olive grove and white Tunisian architecture, just minutes from the sea in Tazarka.',
    'maisonHotesPage.card3h': 'Two formulas, one villa',
    'maisonHotesPage.card3p': 'Seasonal rental of the whole villa and the guest house are not two different properties: it is the same Villa Dar Aïcha, offered as two formulas depending on the time of year.',
    'maisonHotesPage.link1': 'Discover the villa for high-season seasonal rental',
    'maisonHotesPage.k2': 'Accommodation',
    'maisonHotesPage.h2_2': 'Air-conditioned suites, from 255 TND a night',
    'maisonHotesPage.lede3': 'Every suite is air-conditioned and has its own private bathroom. Breakfast included and access to the shared spaces — garden, pool depending on the season.',
    'maisonHotesPage.suite1h': 'Suite 1',
    'maisonHotesPage.suite1p': 'Air-conditioned suite with private bathroom and white bed linen.',
    'maisonHotesPage.suite3h': 'Suite 3',
    'maisonHotesPage.suite3p': 'Air-conditioned suite with private bathroom, on the garden level.',
    'maisonHotesPage.suite6h': 'Hssin Suite',
    'maisonHotesPage.suite6p': 'Upstairs suite with access to the panoramic terrace.',
    'maisonHotesPage.suite9h': 'Suite 9',
    'maisonHotesPage.suite9p': 'Upstairs air-conditioned suite with private bathroom and access to the panoramic terrace.',
    'maisonHotesPage.priceUnit': '/ night, breakfast included',
    'maisonHotesPage.link2': 'See the villa\'s 9 suites',
    'maisonHotesPage.k3': 'Shared spaces',
    'maisonHotesPage.h2_3': 'Garden, pool, lounges and dining area',
    'maisonHotesPage.lede4': 'Guest house guests enjoy the same living spaces as the villa: gardens, lounges opening onto the patio, kitchen and pool depending on the season.',
    'maisonHotesPage.k4': 'Breakfast & meals',
    'maisonHotesPage.h2_4': 'Breakfast included every morning',
    'maisonHotesPage.li1': 'Breakfast included in the suite rate',
    'maisonHotesPage.li2': 'Other meals available on request, to arrange with the host',
    'maisonHotesPage.li3': 'Access to the shared kitchen for self-catered meals',
    'maisonHotesPage.p1': 'There is no fixed restaurant menu: for an on-site lunch or dinner, contact the host to arrange a quote suited to your stay.',
    'maisonHotesPage.k5': 'Ideal for',
    'maisonHotesPage.h2_5': 'A setting suited to several types of travellers',
    'maisonHotesPage.am1': 'Families',
    'maisonHotesPage.am2': 'Couples travelling together',
    'maisonHotesPage.am3': 'Small groups of friends outside the high season',
    'maisonHotesPage.am4': 'Individual travellers passing through Cap Bon',
    'maisonHotesPage.ctaKicker': 'Book',
    'maisonHotesPage.ctaH2': 'Book your suite at the guest house',
    'maisonHotesPage.ctaLede': 'Tell us your dates and the number of guests, and we will reply quickly by WhatsApp or e-mail.',
    'maisonHotesPage.ctaWhatsapp': 'Message us on WhatsApp',
    'maisonHotesPage.crossLink1': 'Whole-villa rental during the high season',
    'maisonHotesPage.crossLink2': 'Groups & retreats, private hire outside season',
    'groupesPage.breadcrumb': 'Groups & Retreats',
    'groupesPage.badge1': 'Up to 20-25 people',
    'groupesPage.badge2': 'Private hire outside high season',
    'groupesPage.badge3': '4 hectares · Cap Bon',
    'groupesPage.h1': 'Groups, seminars & retreats at Dar Aïcha',
    'groupesPage.lede': 'Hire the whole villa outside the high season for a corporate seminar, team building, a wellness or yoga retreat, an olive-oil themed stay, or an extended family gathering.',
    'groupesPage.cta1': 'Request a group quote',
    'groupesPage.cta2': 'See the rates',
    'groupesPage.k1': 'Why Dar Aïcha',
    'groupesPage.h2_1': 'A whole estate for your group',
    'groupesPage.lede2': 'Set on 4 hectares of Koroneiki olive groves, Villa Dar Aïcha offers a calm setting and generous outdoor spaces to host and accommodate a group on site.',
    'groupesPage.stat1': 'Koroneiki olive grove',
    'groupesPage.stat2': 'Air-conditioned suites',
    'groupesPage.stat3': 'People accommodated on site',
    'groupesPage.stat4': 'Minimum nights',
    'groupesPage.k2': 'Possible formats',
    'groupesPage.h2_2': 'Four ways to have Dar Aïcha to yourselves',
    'groupesPage.format1h': 'Corporate seminar & team building',
    'groupesPage.format1p': 'Bring your teams together in an inspiring setting, with the gardens, terraces and pool as breathing spaces between work sessions.',
    'groupesPage.format2h': 'Wellness or yoga retreat',
    'groupesPage.format2p': 'The calm of the estate, its gardens and terraces are well suited to wellness or yoga retreats, away from the bustle.',
    'groupesPage.format3h': 'Olive-oil themed stay',
    'groupesPage.format3p': 'Centred on the harvest and olive-oil tasting of the estate, on request, as part of a group stay on the 4-hectare olive grove.',
    'groupesPage.format4h': 'Family gathering or group of friends',
    'groupesPage.format4p': 'The whole villa for an extended family gathering or a group of friends, with 9 suites and generous shared spaces.',
    'groupesPage.k3': 'Accommodation & rates',
    'groupesPage.h2_3': 'A tapering rate based on the length of stay',
    'groupesPage.lede3': 'Rates for the whole villa, for up to 20 people accommodated with breakfast included. Private hire is open from 10 participants up to 25 people.',
    'groupesPage.tarif1h': '1 to 2 nights',
    'groupesPage.tarif2h': '3 to 5 nights',
    'groupesPage.tarif3h': '6 nights or more',
    'groupesPage.perNight': '/ night',
    'groupesPage.tarifLi1': 'Whole-villa rate for up to 20 people accommodated, breakfast included',
    'groupesPage.tarifLi2': '+120 TND / night per additional person, up to 25 people in total',
    'groupesPage.tarifLi3': 'Catering as an option: half board 100 to 120 TND / person / night',
    'groupesPage.tarifLi4': 'Full board with an on-site chef: 150 to 180 TND / person / night',
    'groupesPage.tarifLi5': '30% deposit on confirmation, 3-night minimum stay',
    'groupesPage.tarifLi6': 'Private hire open from 10 participants up to 25 people',
    'groupesPage.wifiNote': 'Wi-Fi is not guaranteed by default: its availability should be confirmed with the host when booking.',
    'groupesPage.k4': 'Available spaces',
    'groupesPage.h2_4': 'Garden, terraces, pool and lounges for your workshops',
    'groupesPage.lede4': 'Olive grove visits and olive-oil tasting introductions are offered on request, to be built into your stay\'s programme.',
    'groupesPage.k5': 'Your request',
    'groupesPage.h2_5': 'Request a quote for your group',
    'groupesPage.lede5': 'Describe your project: we will get back to you with a proposal suited to the number of participants and the length of stay.',
    'groupesPage.labelOrg': 'Organisation or group name',
    'groupesPage.labelEmail': 'E-mail',
    'groupesPage.labelTelephone': 'Phone / WhatsApp',
    'groupesPage.labelParticipants': 'Number of participants',
    'groupesPage.labelDates': 'Planned dates',
    'groupesPage.placeholderDates': 'e.g. 10 to 13 November 2026',
    'groupesPage.labelType': 'Type of stay',
    'groupesPage.opt1': 'Corporate seminar / team building',
    'groupesPage.opt2': 'Wellness or yoga retreat',
    'groupesPage.opt3': 'Olive-oil themed stay',
    'groupesPage.opt4': 'Family gathering or group of friends',
    'groupesPage.opt5': 'Other',
    'groupesPage.labelMessage': 'Message',
    'groupesPage.submit': 'Request a group quote',
    'groupesPage.rgpd': 'The information you send is used only to respond to your request.',
    'groupesPage.successMsg': 'Thank you, your group quote request has been received. We will get back to you shortly.',
    'groupesPage.coordH3': 'Another way to reach us',
    'groupesPage.coordLede': 'Prefer a direct message? Choose the channel that suits you.',
    'groupesPage.ctaWhatsapp': 'Message us on WhatsApp',
    'groupesPage.contactAccueil': 'On-site host (Fatma):',
    'groupesPage.ctaKicker': 'Continue exploring',
    'groupesPage.ctaH2': 'Discover our other formulas too',
    'groupesPage.ctaLede': 'An individual stay outside a group booking, or a discovery of our estate-grown Koroneiki olive oil.',
    'groupesPage.crossLink1': 'Guest House',
    'groupesPage.crossLink2': 'Estate & Olive Oil',
    'galeriePage.breadcrumb': 'Gallery',
    'galeriePage.badge1': 'Villa & suites',
    'galeriePage.badge2': 'Pool & gardens',
    'galeriePage.badge3': 'Tazarka · Cap Bon',
    'galeriePage.h1': 'Gallery',
    'galeriePage.lede': 'Suites, pool, gardens and olive grove, lounges, patios and kitchen — a photo overview of Villa Dar Aïcha in Tazarka.',
    'galeriePage.k1': 'Villa & suites',
    'galeriePage.villaTitle': 'The villa and its suites',
    'galeriePage.k2': 'Pool & terraces',
    'galeriePage.poolTitle': 'Infinity pool and terraces',
    'galeriePage.k3': 'Garden & olive grove',
    'galeriePage.gardenTitle': 'The garden and the 4-hectare olive grove',
    'galeriePage.k4': 'Lounges & patios',
    'galeriePage.salonsTitle': 'Indoor lounges and patios',
    'galeriePage.k5': 'Kitchen & meals',
    'galeriePage.kitchenTitle': 'Indoor kitchen, outdoor kitchen and dining room',
    'galeriePage.ctaKicker': 'Want to see more?',
    'galeriePage.ctaH2': 'Request your personalised quote',
    'galeriePage.ctaLede': 'A suite stay, whole-villa private hire, a group, a retreat or a wedding — tell us about your project.',
    'galeriePage.cta1': 'Request a quote',
    'villaPage.espacesH2': 'Living rooms, patio and kitchens made for gathering',
    'villaPage.espacesKicker': 'Living Spaces',
    'villaPage.espacesLede': 'Beyond the suites, Dar Aïcha is lived in through its shared spaces: majlis-style living rooms, a central zellige patio, an indoor kitchen opening onto the pool, an outdoor kitchen with bar and barbecue corner, terraces and a generous dining room.',
    'villaPage.patioH2': 'A zellige fountain at the heart of the villa',
    'villaPage.patioKicker': 'Central Patio',
    'villaPage.patioP': 'The vaulted patio distributes the living spaces around a tiered zellige fountain, in true Tunis tradition. Stone colonnades and a shaded dining corner make it a place to pass through and unwind at any time of day.',
    'villaPage.cuisineH2': 'An open indoor kitchen, an outdoor kitchen for grilling',
    'villaPage.cuisineKicker': 'Kitchens',
    'villaPage.cuisineP': 'A central granite island and 5-burner stove indoors; a marble bar counter and sheltered barbecue corner outdoors, facing the olive grove. Everything needed to cook as a family or host a casual outdoor meal.',
    'villaPage.extH2': 'Infinity pool, garden and olive grove',
    'villaPage.extKicker': 'Outdoors',
    'villaPage.extLede': 'The villa opens onto 4 hectares of gardens and olive grove, with an infinity pool, a swing corner for children, and shaded spots to enjoy Cap Bon at any hour.',
    'villaPage.sejoursH2': 'A villa suited to every occasion',
    'villaPage.sejoursKicker': 'Who It\'s For',
    'villaPage.sej1h': 'With Family',
    'villaPage.sej1p': 'Air-conditioned suites, a pool and a swing corner for the children — a serene setting for several generations together.',
    'villaPage.sej2h': 'With Friends',
    'villaPage.sej2p': '9 independent suites, generous shared spaces and an infinity pool for a convivial group stay.',
    'villaPage.sej3h': 'An Intimate Celebration',
    'villaPage.sej3p': 'A birthday, a reunion or an occasion worth marking, in a private setting surrounded by olive trees and gardens.',
    'villaPage.sej4h': 'A Cap Bon Getaway',
    'villaPage.sej4p': 'Minutes from the beaches of Nabeul and Maamoura, for a stay that is both seaside and countryside.',
    'villaPage.infosH2': 'What to know before your stay',
    'villaPage.infosKicker': 'Practical Information',
    'villaPage.pra1h': 'Arrival & Departure',
    'villaPage.pra1p': 'Check-in from 3pm, check-out at 11am. A personalised welcome is provided on site.',
    'villaPage.pra2h': 'Parking',
    'villaPage.pra2p': 'Private parking available on the property.',
    'villaPage.pra3h': 'House Rules',
    'villaPage.pra3link': 'Stay Conditions',
    'villaPage.pra3p': 'Detailed stay conditions (cancellation, security deposit, house rules) are set out on the ',
    'villaPage.galH2': 'The spaces in pictures',
    'villaPage.galKicker': 'Gallery',
    'villaPage.galLede': 'A glimpse of the suites, living rooms and outdoor spaces. See all the photos on the ',
    'villaPage.galLink': 'Gallery',

    // ---------- Homepage (index.html) ----------
    'hero.badge1': 'Tazarka · Cap Bon',
    'hero.badge2': '9 suites · Pool',
    'hero.badge3': '4 hectares · Olive grove',
    'hero.h1': 'Dar Aïcha, a charming estate on Cap Bon',
    'hero.lede': 'In Tazarka, among olive trees, Mediterranean light and the art of hospitality.',
    'hero.cta1': 'Request a quote',
    'hero.cta2': 'Discover the villa',
    'hero.scroll': 'Scroll',
    'stats.label1': 'air-conditioned suites',
    'stats.label2': 'people depending on configuration',
    'stats.label3': 'of Koroneiki olive groves',
    'stats.label4': 'garden and outdoor areas',
    'stats.label5': 'private receptions, subject to confirmed capacity',
    'univers.kicker': 'Three ways to experience Dar Aïcha',
    'univers.h2': 'Stay, celebrate or immerse yourself in the estate',
    'univers.card1Kicker': 'Stay',
    'univers.card1H3': 'The villa and guesthouse',
    'univers.card1P': '9 suites, pool and garden — exclusive rental in high season, or a guesthouse the rest of the year.',
    'univers.card2Kicker': 'Celebrate',
    'univers.card2H3': 'Weddings and events',
    'univers.card2P': 'A private setting between olive trees and the Mediterranean for your receptions, on request.',
    'univers.card3Kicker': 'Immerse yourself',
    'univers.card3H3': 'The estate and olive grove',
    'univers.card3P': '4 hectares of Koroneiki olive trees and an extra virgin olive oil produced on site.',
    'villaPreview.kicker': 'The villa',
    'villaPreview.h2': '9 suites, a patio, living rooms opening onto the pool',
    'villaPreview.lede': 'Majlis lounges, indoor and outdoor kitchens, terraces, garden and infinity pool: Dar Aïcha feels like a large family home, surrounded by its olive grove.',
    'villaPreview.link': 'Discover the villa',
    'saison.kicker': 'Depending on the season',
    'saison.h2': 'The villa privatized in high season, a guesthouse the rest of the year',
    'saison.card1H3': 'High season',
    'saison.card1P': 'The entire villa can be privatized for your family, friends or group — 9 suites and all common areas just for you.',
    'saison.card1Link': 'Discover the villa',
    'saison.card2H3': 'Low season',
    'saison.card2P': 'Outside high season, Dar Aïcha becomes a guesthouse: individual rooms and suites for a more intimate stay.',
    'saison.card2Link': 'Discover the guesthouse',
    'evenementsHome.kicker': 'Celebrate',
    'evenementsHome.h2': 'A private reception venue, on request',
    'evenementsHome.lede': 'Garden, pool, terraces and reception areas: Dar Aïcha welcomes your weddings, engagements and private events in a setting between olive trees and the Mediterranean. Every package is quoted individually, depending on the season, confirmed capacity and applicable permits.',
    'evenementsHome.link': 'Plan an event',
    'groupesHome.kicker': 'Gather',
    'groupesHome.h2': 'Wellness retreats, workshops, seminars and group stays',
    'groupesHome.lede': 'Privatize the entire villa outside high season for a wellness or yoga retreat, a corporate seminar, an extended family stay or an olive-growing themed stay.',
    'groupesHome.link': 'Plan a group stay',
    'domaineHome.kicker': 'Immerse yourself',
    'domaineHome.h2': '4 hectares of Koroneiki olive trees, an estate-produced olive oil',
    'domaineHome.lede': 'The Dar Aïcha estate grows 4 hectares of Koroneiki olive trees in Tazarka. The extra virgin olive oil produced on site is available to visitors and can be discovered during a terroir-themed stay on the property.',
    'domaineHome.link': 'Discover the estate',
    'galSelect.kicker': 'In pictures',
    'galSelect.h2': 'A glimpse of the Dar Aïcha estate',
    'galSelect.link': 'See the full gallery',
    'accesHome.kicker': 'Location',
    'accesHome.h2': 'Tazarka, between the sea and the countryside of Cap Bon',
    'accesHome.lede': 'Dar Aïcha is located in Tazarka, in the Nabeul governorate, on the Cap Bon peninsula — a few minutes from the beaches of Nabeul and Maamoura, between Tunis-Carthage and Enfidha-Hammamet airports.',
    'accesHome.link': "See how to reach Dar Aïcha",
    'convFinale.h2': 'Imagine your stay at Dar Aïcha',
    'convFinale.lede': 'A stay, a private reception, or simply a visit to the estate — contact us on WhatsApp, by email, or through our quote request form.',
    'convFinale.cta1': 'Request a quote',
    'convFinale.cta2': 'Contact us on WhatsApp',
  };

  var STORAGE_KEY = 'siteLang';
  var toggleBtn = document.querySelector('[data-lang-toggle]');

  function setI18nText(el, text) {
    var hasElementChild = false;
    for (var i = 0; i < el.childNodes.length; i++) {
      if (el.childNodes[i].nodeType === 1) { hasElementChild = true; break; }
    }
    if (!hasElementChild) {
      el.textContent = text;
      return;
    }
    // Preserve element children (e.g. inline SVG icons) — only replace text nodes.
    var textSet = false;
    Array.prototype.slice.call(el.childNodes).forEach(function (node) {
      if (node.nodeType === 3) {
        if (!textSet) { node.textContent = text; textSet = true; }
        else { node.textContent = ''; }
      }
    });
    if (!textSet) el.insertBefore(document.createTextNode(text), el.firstChild);
  }

  function applyLang(lang) {
    document.querySelectorAll('[data-i18n]').forEach(function (el) {
      var key = el.getAttribute('data-i18n');
      if (el.dataset.frText === undefined) el.dataset.frText = el.textContent;
      setI18nText(el, lang === 'en' && EN[key] !== undefined ? EN[key] : el.dataset.frText);
    });
    document.querySelectorAll('[data-i18n-alt]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-alt');
      if (el.dataset.frAlt === undefined) el.dataset.frAlt = el.getAttribute('alt') || '';
      el.setAttribute('alt', lang === 'en' && EN[key] !== undefined ? EN[key] : el.dataset.frAlt);
    });
    document.querySelectorAll('[data-i18n-aria]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-aria');
      if (el.dataset.frAria === undefined) el.dataset.frAria = el.getAttribute('aria-label') || '';
      el.setAttribute('aria-label', lang === 'en' && EN[key] !== undefined ? EN[key] : el.dataset.frAria);
    });
    document.querySelectorAll('[data-i18n-attr-title]').forEach(function (el) {
      var key = el.getAttribute('data-i18n-attr-title');
      if (el.dataset.frTitle === undefined) el.dataset.frTitle = el.getAttribute('title') || '';
      el.setAttribute('title', lang === 'en' && EN[key] !== undefined ? EN[key] : el.dataset.frTitle);
    });

    document.documentElement.setAttribute('lang', lang);
    try { localStorage.setItem(STORAGE_KEY, lang); } catch (e) {}

    if (toggleBtn) {
      toggleBtn.textContent = lang === 'fr' ? 'EN' : 'FR';
      toggleBtn.setAttribute('aria-label', lang === 'fr' ? 'Switch to English' : 'Passer en français');
      toggleBtn.setAttribute('data-current-lang', lang);
    }
  }

  var saved = 'fr';
  try { saved = localStorage.getItem(STORAGE_KEY) || 'fr'; } catch (e) {}
  applyLang(saved);

  if (toggleBtn) {
    toggleBtn.addEventListener('click', function () {
      var current = toggleBtn.getAttribute('data-current-lang') || 'fr';
      applyLang(current === 'fr' ? 'en' : 'fr');
    });
  }
})();
// script.js — Dar Aïcha Tazarka

// ---------- Theme toggle ----------
(function () {
  const t = document.querySelector('[data-theme-toggle]');
  const r = document.documentElement;
  let d = matchMedia('(prefers-color-scheme:dark)').matches ? 'dark' : 'light';
  r.setAttribute('data-theme', d);
  updateIcon();
  t &&
    t.addEventListener('click', () => {
      d = d === 'dark' ? 'light' : 'dark';
      r.setAttribute('data-theme', d);
      updateIcon();
    });
  function updateIcon() {
    if (!t) return;
    t.setAttribute('aria-label', 'Passer en mode ' + (d === 'dark' ? 'clair' : 'sombre'));
    t.innerHTML =
      d === 'dark'
        ? '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="5"/><path d="M12 1v2M12 21v2M4.22 4.22l1.42 1.42M18.36 18.36l1.42 1.42M1 12h2M21 12h2M4.22 19.78l1.42-1.42M18.36 5.64l1.42-1.42"/></svg>'
        : '<svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 12.79A9 9 0 1 1 11.21 3 7 7 0 0 0 21 12.79z"/></svg>';
  }
})();

// ---------- Mobile nav ----------
(function () {
  const toggle = document.querySelector('[data-nav-toggle]');
  const nav = document.querySelector('[data-main-nav]');
  if (!toggle || !nav) return;
  toggle.addEventListener('click', () => {
    const open = nav.classList.toggle('is-open');
    toggle.setAttribute('aria-expanded', open ? 'true' : 'false');
  });
  nav.querySelectorAll('a').forEach((a) =>
    a.addEventListener('click', () => {
      nav.classList.remove('is-open');
      toggle.setAttribute('aria-expanded', 'false');
    })
  );
})();

// ---------- Scroll reveal ----------
(function () {
  const els = document.querySelectorAll('[data-reveal]');
  if (!('IntersectionObserver' in window) || !els.length) {
    els.forEach((el) => el.classList.add('is-visible'));
    return;
  }
  const io = new IntersectionObserver(
    (entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add('is-visible');
          io.unobserve(entry.target);
        }
      });
    },
    { threshold: 0.12, rootMargin: '0px 0px -40px 0px' }
  );
  els.forEach((el) => io.observe(el));
})();

// ---------- Lightbox ----------
(function () {
  const lightbox = document.querySelector('[data-lightbox]');
  if (!lightbox) return;
  const img = lightbox.querySelector('img');
  const closeBtn = lightbox.querySelector('[data-lightbox-close]');
  document.querySelectorAll('[data-lightbox-trigger]').forEach((el) => {
    el.addEventListener('click', () => {
      const src = el.getAttribute('data-full') || el.src;
      img.src = src;
      img.alt = el.alt || '';
      lightbox.classList.add('is-open');
    });
  });
  function close() {
    lightbox.classList.remove('is-open');
    img.src = '';
  }
  closeBtn && closeBtn.addEventListener('click', close);
  lightbox.addEventListener('click', (e) => {
    if (e.target === lightbox) close();
  });
  document.addEventListener('keydown', (e) => {
    if (e.key === 'Escape') close();
  });
})();

// ---------- Booking form (no backend — mailto/WhatsApp handoff) ----------
(function () {
  const form = document.querySelector('[data-booking-form]');
  if (!form) return;
  form.addEventListener('submit', (e) => {
    e.preventDefault();
    const data = new FormData(form);
    const nom = data.get('nom') || '';
    const arrivee = data.get('arrivee') || '';
    const depart = data.get('depart') || '';
    const voyageurs = data.get('voyageurs') || '';
    const message = data.get('message') || '';
    const type = data.get('type') || 'Séjour';
    const text = encodeURIComponent(
      `Bonjour, je suis ${nom}. Je souhaite une demande de devis pour : ${type}.\nArrivée : ${arrivee}\nDépart : ${depart}\nNombre de personnes : ${voyageurs}\nMessage : ${message}`
    );
    window.open(`https://wa.me/68987717863?text=${text}`, '_blank');
  });
})();

// ---------- Current year ----------
(function () {
  const y = document.querySelector('[data-year]');
  if (y) y.textContent = new Date().getFullYear();
})();
